/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as ProtectedStudentRouteRouteImport } from './routes/_protected/student/route'
import { Route as ProtectedInstructorRouteRouteImport } from './routes/_protected/instructor/route'
import { Route as ProtectedAdminRouteRouteImport } from './routes/_protected/admin/route'
import { Route as ProtectedStudentSessionsRouteRouteImport } from './routes/_protected/student/sessions/route'
import { Route as ProtectedInstructorSessionsRouteRouteImport } from './routes/_protected/instructor/sessions/route'
import { Route as ProtectedAdminUsersRouteRouteImport } from './routes/_protected/admin/users/route'
import { Route as ProtectedAdminSessionsRouteRouteImport } from './routes/_protected/admin/sessions/route'
import { Route as ProtectedAdminPostsRouteRouteImport } from './routes/_protected/admin/posts/route'
import { Route as ProtectedAdminPaymentsRouteRouteImport } from './routes/_protected/admin/payments/route'
import { Route as ProtectedAdminModulesRouteRouteImport } from './routes/_protected/admin/modules/route'
import { Route as ProtectedAdminLessonsRouteRouteImport } from './routes/_protected/admin/lessons/route'
import { Route as ProtectedAdminFormationsRouteRouteImport } from './routes/_protected/admin/formations/route'
import { Route as ProtectedStudentDashboardIndexRouteImport } from './routes/_protected/student/dashboard/index'
import { Route as ProtectedInstructorDashboardIndexRouteImport } from './routes/_protected/instructor/dashboard/index'
import { Route as ProtectedAdminDashboardIndexRouteImport } from './routes/_protected/admin/dashboard/index'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedStudentRouteRoute = ProtectedStudentRouteRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedInstructorRouteRoute =
  ProtectedInstructorRouteRouteImport.update({
    id: '/instructor',
    path: '/instructor',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedAdminRouteRoute = ProtectedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedStudentSessionsRouteRoute =
  ProtectedStudentSessionsRouteRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => ProtectedStudentRouteRoute,
  } as any)
const ProtectedInstructorSessionsRouteRoute =
  ProtectedInstructorSessionsRouteRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => ProtectedInstructorRouteRoute,
  } as any)
const ProtectedAdminUsersRouteRoute =
  ProtectedAdminUsersRouteRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedAdminSessionsRouteRoute =
  ProtectedAdminSessionsRouteRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedAdminPostsRouteRoute =
  ProtectedAdminPostsRouteRouteImport.update({
    id: '/posts',
    path: '/posts',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedAdminPaymentsRouteRoute =
  ProtectedAdminPaymentsRouteRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedAdminModulesRouteRoute =
  ProtectedAdminModulesRouteRouteImport.update({
    id: '/modules',
    path: '/modules',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedAdminLessonsRouteRoute =
  ProtectedAdminLessonsRouteRouteImport.update({
    id: '/lessons',
    path: '/lessons',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedAdminFormationsRouteRoute =
  ProtectedAdminFormationsRouteRouteImport.update({
    id: '/formations',
    path: '/formations',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedStudentDashboardIndexRoute =
  ProtectedStudentDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => ProtectedStudentRouteRoute,
  } as any)
const ProtectedInstructorDashboardIndexRoute =
  ProtectedInstructorDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => ProtectedInstructorRouteRoute,
  } as any)
const ProtectedAdminDashboardIndexRoute =
  ProtectedAdminDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/instructor': typeof ProtectedInstructorRouteRouteWithChildren
  '/student': typeof ProtectedStudentRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/admin/formations': typeof ProtectedAdminFormationsRouteRoute
  '/admin/lessons': typeof ProtectedAdminLessonsRouteRoute
  '/admin/modules': typeof ProtectedAdminModulesRouteRoute
  '/admin/payments': typeof ProtectedAdminPaymentsRouteRoute
  '/admin/posts': typeof ProtectedAdminPostsRouteRoute
  '/admin/sessions': typeof ProtectedAdminSessionsRouteRoute
  '/admin/users': typeof ProtectedAdminUsersRouteRoute
  '/instructor/sessions': typeof ProtectedInstructorSessionsRouteRoute
  '/student/sessions': typeof ProtectedStudentSessionsRouteRoute
  '/admin/dashboard': typeof ProtectedAdminDashboardIndexRoute
  '/instructor/dashboard': typeof ProtectedInstructorDashboardIndexRoute
  '/student/dashboard': typeof ProtectedStudentDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/instructor': typeof ProtectedInstructorRouteRouteWithChildren
  '/student': typeof ProtectedStudentRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/admin/formations': typeof ProtectedAdminFormationsRouteRoute
  '/admin/lessons': typeof ProtectedAdminLessonsRouteRoute
  '/admin/modules': typeof ProtectedAdminModulesRouteRoute
  '/admin/payments': typeof ProtectedAdminPaymentsRouteRoute
  '/admin/posts': typeof ProtectedAdminPostsRouteRoute
  '/admin/sessions': typeof ProtectedAdminSessionsRouteRoute
  '/admin/users': typeof ProtectedAdminUsersRouteRoute
  '/instructor/sessions': typeof ProtectedInstructorSessionsRouteRoute
  '/student/sessions': typeof ProtectedStudentSessionsRouteRoute
  '/admin/dashboard': typeof ProtectedAdminDashboardIndexRoute
  '/instructor/dashboard': typeof ProtectedInstructorDashboardIndexRoute
  '/student/dashboard': typeof ProtectedStudentDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_protected/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/_protected/instructor': typeof ProtectedInstructorRouteRouteWithChildren
  '/_protected/student': typeof ProtectedStudentRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/_protected/admin/formations': typeof ProtectedAdminFormationsRouteRoute
  '/_protected/admin/lessons': typeof ProtectedAdminLessonsRouteRoute
  '/_protected/admin/modules': typeof ProtectedAdminModulesRouteRoute
  '/_protected/admin/payments': typeof ProtectedAdminPaymentsRouteRoute
  '/_protected/admin/posts': typeof ProtectedAdminPostsRouteRoute
  '/_protected/admin/sessions': typeof ProtectedAdminSessionsRouteRoute
  '/_protected/admin/users': typeof ProtectedAdminUsersRouteRoute
  '/_protected/instructor/sessions': typeof ProtectedInstructorSessionsRouteRoute
  '/_protected/student/sessions': typeof ProtectedStudentSessionsRouteRoute
  '/_protected/admin/dashboard/': typeof ProtectedAdminDashboardIndexRoute
  '/_protected/instructor/dashboard/': typeof ProtectedInstructorDashboardIndexRoute
  '/_protected/student/dashboard/': typeof ProtectedStudentDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/instructor'
    | '/student'
    | '/login'
    | '/register'
    | '/demo/tanstack-query'
    | '/admin/formations'
    | '/admin/lessons'
    | '/admin/modules'
    | '/admin/payments'
    | '/admin/posts'
    | '/admin/sessions'
    | '/admin/users'
    | '/instructor/sessions'
    | '/student/sessions'
    | '/admin/dashboard'
    | '/instructor/dashboard'
    | '/student/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/instructor'
    | '/student'
    | '/login'
    | '/register'
    | '/demo/tanstack-query'
    | '/admin/formations'
    | '/admin/lessons'
    | '/admin/modules'
    | '/admin/payments'
    | '/admin/posts'
    | '/admin/sessions'
    | '/admin/users'
    | '/instructor/sessions'
    | '/student/sessions'
    | '/admin/dashboard'
    | '/instructor/dashboard'
    | '/student/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_protected/admin'
    | '/_protected/instructor'
    | '/_protected/student'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/demo/tanstack-query'
    | '/_protected/admin/formations'
    | '/_protected/admin/lessons'
    | '/_protected/admin/modules'
    | '/_protected/admin/payments'
    | '/_protected/admin/posts'
    | '/_protected/admin/sessions'
    | '/_protected/admin/users'
    | '/_protected/instructor/sessions'
    | '/_protected/student/sessions'
    | '/_protected/admin/dashboard/'
    | '/_protected/instructor/dashboard/'
    | '/_protected/student/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/student': {
      id: '/_protected/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof ProtectedStudentRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/instructor': {
      id: '/_protected/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof ProtectedInstructorRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/student/sessions': {
      id: '/_protected/student/sessions'
      path: '/sessions'
      fullPath: '/student/sessions'
      preLoaderRoute: typeof ProtectedStudentSessionsRouteRouteImport
      parentRoute: typeof ProtectedStudentRouteRoute
    }
    '/_protected/instructor/sessions': {
      id: '/_protected/instructor/sessions'
      path: '/sessions'
      fullPath: '/instructor/sessions'
      preLoaderRoute: typeof ProtectedInstructorSessionsRouteRouteImport
      parentRoute: typeof ProtectedInstructorRouteRoute
    }
    '/_protected/admin/users': {
      id: '/_protected/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof ProtectedAdminUsersRouteRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/sessions': {
      id: '/_protected/admin/sessions'
      path: '/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof ProtectedAdminSessionsRouteRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/posts': {
      id: '/_protected/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof ProtectedAdminPostsRouteRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/payments': {
      id: '/_protected/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof ProtectedAdminPaymentsRouteRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/modules': {
      id: '/_protected/admin/modules'
      path: '/modules'
      fullPath: '/admin/modules'
      preLoaderRoute: typeof ProtectedAdminModulesRouteRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/lessons': {
      id: '/_protected/admin/lessons'
      path: '/lessons'
      fullPath: '/admin/lessons'
      preLoaderRoute: typeof ProtectedAdminLessonsRouteRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/formations': {
      id: '/_protected/admin/formations'
      path: '/formations'
      fullPath: '/admin/formations'
      preLoaderRoute: typeof ProtectedAdminFormationsRouteRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/student/dashboard/': {
      id: '/_protected/student/dashboard/'
      path: '/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof ProtectedStudentDashboardIndexRouteImport
      parentRoute: typeof ProtectedStudentRouteRoute
    }
    '/_protected/instructor/dashboard/': {
      id: '/_protected/instructor/dashboard/'
      path: '/dashboard'
      fullPath: '/instructor/dashboard'
      preLoaderRoute: typeof ProtectedInstructorDashboardIndexRouteImport
      parentRoute: typeof ProtectedInstructorRouteRoute
    }
    '/_protected/admin/dashboard/': {
      id: '/_protected/admin/dashboard/'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof ProtectedAdminDashboardIndexRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
  }
}

interface ProtectedAdminRouteRouteChildren {
  ProtectedAdminFormationsRouteRoute: typeof ProtectedAdminFormationsRouteRoute
  ProtectedAdminLessonsRouteRoute: typeof ProtectedAdminLessonsRouteRoute
  ProtectedAdminModulesRouteRoute: typeof ProtectedAdminModulesRouteRoute
  ProtectedAdminPaymentsRouteRoute: typeof ProtectedAdminPaymentsRouteRoute
  ProtectedAdminPostsRouteRoute: typeof ProtectedAdminPostsRouteRoute
  ProtectedAdminSessionsRouteRoute: typeof ProtectedAdminSessionsRouteRoute
  ProtectedAdminUsersRouteRoute: typeof ProtectedAdminUsersRouteRoute
  ProtectedAdminDashboardIndexRoute: typeof ProtectedAdminDashboardIndexRoute
}

const ProtectedAdminRouteRouteChildren: ProtectedAdminRouteRouteChildren = {
  ProtectedAdminFormationsRouteRoute: ProtectedAdminFormationsRouteRoute,
  ProtectedAdminLessonsRouteRoute: ProtectedAdminLessonsRouteRoute,
  ProtectedAdminModulesRouteRoute: ProtectedAdminModulesRouteRoute,
  ProtectedAdminPaymentsRouteRoute: ProtectedAdminPaymentsRouteRoute,
  ProtectedAdminPostsRouteRoute: ProtectedAdminPostsRouteRoute,
  ProtectedAdminSessionsRouteRoute: ProtectedAdminSessionsRouteRoute,
  ProtectedAdminUsersRouteRoute: ProtectedAdminUsersRouteRoute,
  ProtectedAdminDashboardIndexRoute: ProtectedAdminDashboardIndexRoute,
}

const ProtectedAdminRouteRouteWithChildren =
  ProtectedAdminRouteRoute._addFileChildren(ProtectedAdminRouteRouteChildren)

interface ProtectedInstructorRouteRouteChildren {
  ProtectedInstructorSessionsRouteRoute: typeof ProtectedInstructorSessionsRouteRoute
  ProtectedInstructorDashboardIndexRoute: typeof ProtectedInstructorDashboardIndexRoute
}

const ProtectedInstructorRouteRouteChildren: ProtectedInstructorRouteRouteChildren =
  {
    ProtectedInstructorSessionsRouteRoute:
      ProtectedInstructorSessionsRouteRoute,
    ProtectedInstructorDashboardIndexRoute:
      ProtectedInstructorDashboardIndexRoute,
  }

const ProtectedInstructorRouteRouteWithChildren =
  ProtectedInstructorRouteRoute._addFileChildren(
    ProtectedInstructorRouteRouteChildren,
  )

interface ProtectedStudentRouteRouteChildren {
  ProtectedStudentSessionsRouteRoute: typeof ProtectedStudentSessionsRouteRoute
  ProtectedStudentDashboardIndexRoute: typeof ProtectedStudentDashboardIndexRoute
}

const ProtectedStudentRouteRouteChildren: ProtectedStudentRouteRouteChildren = {
  ProtectedStudentSessionsRouteRoute: ProtectedStudentSessionsRouteRoute,
  ProtectedStudentDashboardIndexRoute: ProtectedStudentDashboardIndexRoute,
}

const ProtectedStudentRouteRouteWithChildren =
  ProtectedStudentRouteRoute._addFileChildren(
    ProtectedStudentRouteRouteChildren,
  )

interface ProtectedRouteRouteChildren {
  ProtectedAdminRouteRoute: typeof ProtectedAdminRouteRouteWithChildren
  ProtectedInstructorRouteRoute: typeof ProtectedInstructorRouteRouteWithChildren
  ProtectedStudentRouteRoute: typeof ProtectedStudentRouteRouteWithChildren
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedAdminRouteRoute: ProtectedAdminRouteRouteWithChildren,
  ProtectedInstructorRouteRoute: ProtectedInstructorRouteRouteWithChildren,
  ProtectedStudentRouteRoute: ProtectedStudentRouteRouteWithChildren,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
